LIGHT="""
QWidget{font-family:'Microsoft YaHei','Microsoft YaHei UI';font-size:13px;color:#17223b;background:#f5f7fb} QMainWindow{background:#f5f7fb}
QFrame#card,QScrollArea#card{background:white;border:1px solid #e2e7f0;border-radius:8px} QLabel#title{font-size:22px;font-weight:700} QLabel#section{font-size:16px;font-weight:700} QLabel#muted{color:#748099} QLabel#metric{font-size:22px;font-weight:700;color:#17223b}
QPushButton{background:white;border:1px solid #dce2ec;border-radius:8px;padding:8px 14px} QPushButton:hover{border-color:#2D7FF9;color:#2D7FF9} QPushButton#primary{background:#2D7FF9;color:white;border:0;font-weight:700} QPushButton:disabled{background:#e7eaf0;color:#9aa3b5}
QTextBrowser,QTreeWidget,QListWidget,QTableWidget{background:white;border:1px solid #e2e7f0;border-radius:10px;padding:8px} QHeaderView::section{background:#F3F5F8;color:#596579;border:0;border-bottom:1px solid #DDE3ED;padding:8px;font-weight:600} QLineEdit,QComboBox,QSpinBox{background:white;border:1px solid #dce2ec;border-radius:7px;padding:7px} QComboBox QAbstractItemView{background:#fff;selection-background-color:#EAF2FF;selection-color:#17223b;outline:0} QTabWidget::pane{border:0} QTabBar::tab{padding:10px 18px;background:transparent} QTabBar::tab:selected{color:#2D7FF9;border-bottom:2px solid #2D7FF9} QProgressBar{border:0;background:#e8edf5;border-radius:5px;height:10px} QProgressBar::chunk{background:#2D7FF9;border-radius:5px} QScrollBar:vertical{background:transparent;width:10px;margin:2px} QScrollBar::handle:vertical{background:#C8D0DD;border-radius:5px;min-height:28px} QScrollBar::add-line:vertical,QScrollBar::sub-line:vertical{height:0}
"""
DARK="""
QWidget{font-family:'Microsoft YaHei','Microsoft YaHei UI';font-size:13px;color:#E0E0E0;background:#1E1E1E} QMainWindow{background:#1E1E1E}
QFrame#card,QScrollArea#card{background:#2A2A2A;border:1px solid #3A3A3A;border-radius:8px} QLabel#title{font-size:22px;font-weight:700} QLabel#section{font-size:16px;font-weight:700} QLabel#muted{color:#A6A6A6} QLabel#metric{font-size:22px;font-weight:700;color:#fff}
QPushButton{background:#2A2A2A;border:1px solid #444;border-radius:8px;padding:8px 14px} QPushButton:hover{border-color:#4A9EFF;color:#4A9EFF} QPushButton#primary{background:#4A9EFF;color:#111;border:0;font-weight:700} QPushButton:disabled{background:#333;color:#777}
QTextBrowser,QTreeWidget,QListWidget,QTableWidget{background:#2A2A2A;border:1px solid #3A3A3A;border-radius:10px;padding:8px} QHeaderView::section{background:#303238;color:#D7DCE5;border:0;border-bottom:1px solid #454850;padding:8px;font-weight:600} QLineEdit,QComboBox,QSpinBox{background:#252525;border:1px solid #444;border-radius:7px;padding:7px} QComboBox QAbstractItemView{background:#292B30;selection-background-color:#314E78;selection-color:#fff;outline:0} QTabWidget::pane{border:0} QTabBar::tab{padding:10px 18px;background:transparent} QTabBar::tab:selected{color:#4A9EFF;border-bottom:2px solid #4A9EFF} QProgressBar{border:0;background:#333;border-radius:5px;height:10px} QProgressBar::chunk{background:#4A9EFF;border-radius:5px} QScrollBar:vertical{background:transparent;width:10px;margin:2px} QScrollBar::handle:vertical{background:#555B66;border-radius:5px;min-height:28px} QScrollBar::add-line:vertical,QScrollBar::sub-line:vertical{height:0}
"""
